name: 'Configuration Environment'
type: module
description: 'Allows administrators to manage configuration environments.'
package: Core (Experimental)
# version: VERSION
dependencies:
  - drupal:config

# Information added by Drupal.org packaging script on 2020-02-11
version: '9.0.0-alpha1'
project: 'drupal'
datestamp: 1581447967
